# Despliegue automático de las aplicaciones al hacer commits en las ramas main y demo
# La rama MAIN se despliega en produccion (aplicacion que se usa en el centro)
# La rama DEMO es una rama espejo para hacer pruebas de nuevas funcionalidades
# PRIMERO SE MERGEA EN DEMO Y LUEGO DEMO SE PASA A MAIN, NUNCA AL REVÉS (puedes cargarte la app de producción)

name: Deploy via FTP (main & demo)

on:
  push:
    branches:
      - main
      - demo

jobs:
  ftp-deploy:
    name: Upload to FTP server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set config.php for correct environment
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "Configurando entorno para PRODUCCIÓN"
            sed -i "s/\$prod = false;/\$prod = true;/" config/config.php
            sed -i "s/'prod' => false,/'prod' => true,/" config/config.php
            sed -i "s/:NOMBRECARPETA/evg-reservas-libros-back/g" config/config.php
            sed -i "s|'base_url_front' => .*,|'base_url_front' => 'https://aplicaciones.esvirgua.com/reservas-libros/evg-reservas-libros/',|" config/config.php
          else
            echo "Configurando entorno para DEMO"
            sed -i "s/\$prod = false;/\$prod = true;/" config/config.php
            sed -i "s/'prod' => false,/'prod' => true,/" config/config.php
            sed -i "s/:NOMBRECARPETA/evg-reservas-libros-back-demo/g" config/config.php
            sed -i "s|'base_url_front' => .*,|'base_url_front' => 'https://aplicaciones.esvirgua.com/reservas-libros/evg-reservas-libros-demo/',|" config/config.php
          fi

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ github.ref == 'refs/heads/main' && '/public_html/reservas-libros/evg-reservas-libros-back/' || '/public_html/reservas-libros/evg-reservas-libros-back-demo/' }}
